spring:
  application:
    name: spring-gpt
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: never
      embedding:
        model: ollama
        options:
          temperature: 0.1
          top-p: 0.5
          top-k: 1
          repeat-penalty: 1.1
          num-predict: 1024
          model: mxbai-embed-large
      chat:
        options:
          model: 'gpt-oss'
          temperature: 0.3
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1024
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
        initialize-schema: true
      observations:
        log-query-response: true

logging:
  level:
    org:
      springframework:
        ai:
          vectorstore: debug
          chat:
            client:
              advisor: debug
server:
  port: 9191