
spring:
  security:
    bas
  application:
    name: spring-gpt
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: never
      embedding:
        model: mxbai-embed-large
        options:
          temperature: 0.5
#          top-p: 0.95
#          top-k: 100
#          repeat-penalty: 1.0
#          num-predict: 2048
      chat:
        options:
          model: dolphin-llama3:8b
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1024
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
        initialize-schema: true

logging:
  level:
    org:
      springframework:
        ai:
          vectorstore: debug
          ollama: debug
server:
  port: 9191